dist:
  name: otelcol-dev
  description: Basic OTel Collector distribution for Developers
  output_path: ./otelcol-dev
  otelcol_version: 0.99.0

exporters:
  - gomod:
      go.opentelemetry.io/collector/exporter/debugexporter v0.99.0
  - gomod:
      go.opentelemetry.io/collector/exporter/otlphttpexporter v0.99.0

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.99.0

receivers:
  - gomod: github.com/dynatrace-extensions/netflowreceiver v0.0.0-00010101000000-000000000000
    path: ./netflowreceiver

