dist:
  name: otelcol-dev
  description: Basic OTel Collector distribution for Developers
  output_path: ./otelcol-dev

exporters:
  - gomod:
      go.opentelemetry.io/collector/exporter/debugexporter v0.99.0
  - gomod:
      go.opentelemetry.io/collector/exporter/otlphttpexporter v0.99.0

processors:
  - gomod:
      go.opentelemetry.io/collector/processor/batchprocessor v0.99.0

receivers:
  - gomod: github.com/dynatrace-extensions/netflowreceiver v1.2.0
    path: .

