receivers:
  netflow:
    hostname: "0.0.0.0"
    scheme: netflow
    port: 2055
    sockets: 16
    workers: 32

processors:
  batch:
    send_batch_size: 30 
    timeout: 30s

exporters:
  debug:
  otlphttp:
    endpoint: https://<environment>.live.dynatrace.com/api/v2/otlp
    headers: 
      Authorization: "Api-Token <dynatrace_token>"

service:
  pipelines:
    logs:
      receivers: [netflow]
      processors: [batch]
      exporters: [debug, otlphttp]
  telemetry:
    logs:
      level: debug